/**
 * ID4i API
 * ID4i HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Id4iApi) {
      root.Id4iApi = {};
    }
    root.Id4iApi.SendCustomMessage = factory(root.Id4iApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SendCustomMessage model module.
   * @module model/SendCustomMessage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SendCustomMessage</code>.
   * @alias module:model/SendCustomMessage
   * @class
   * @param data {Object.<String, String>} Custom data in a map. You may use JSON content
   * @param name {String} The name of the message (organisation specific)
   */
  var exports = function(data, name) {
    var _this = this;

    _this['data'] = data;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>SendCustomMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendCustomMessage} obj Optional instance to populate.
   * @return {module:model/SendCustomMessage} The populated <code>SendCustomMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], {'String': 'String'});
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * Custom data in a map. You may use JSON content
   * @member {Object.<String, String>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * The name of the message (organisation specific)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


