/**
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PasswordResetRequest', 'model/PasswordResetVerificationRequest', 'model/RegistrationVerificationTokenPresentation', 'model/SimpleMessageResponse', 'model/UserPresentation', 'model/UserRegistrationRequest', 'model/UserRegistrationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PasswordResetRequest'), require('../model/PasswordResetVerificationRequest'), require('../model/RegistrationVerificationTokenPresentation'), require('../model/SimpleMessageResponse'), require('../model/UserPresentation'), require('../model/UserRegistrationRequest'), require('../model/UserRegistrationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Id4iApi) {
      root.Id4iApi = {};
    }
    root.Id4iApi.AccountcontrollerApi = factory(root.Id4iApi.ApiClient, root.Id4iApi.PasswordResetRequest, root.Id4iApi.PasswordResetVerificationRequest, root.Id4iApi.RegistrationVerificationTokenPresentation, root.Id4iApi.SimpleMessageResponse, root.Id4iApi.UserPresentation, root.Id4iApi.UserRegistrationRequest, root.Id4iApi.UserRegistrationResponse);
  }
}(this, function(ApiClient, PasswordResetRequest, PasswordResetVerificationRequest, RegistrationVerificationTokenPresentation, SimpleMessageResponse, UserPresentation, UserRegistrationRequest, UserRegistrationResponse) {
  'use strict';

  /**
   * Accountcontroller service.
   * @module api/AccountcontrollerApi
   * @version 0.0.1-alpha
   */

  /**
   * Constructs a new AccountcontrollerApi. 
   * @alias module:api/AccountcontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the registerUserUsingPOST operation.
     * @callback module:api/AccountcontrollerApi~registerUserUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRegistrationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * registerUser
     * @param {module:model/UserRegistrationRequest} userRegistration userRegistration
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {module:api/AccountcontrollerApi~registerUserUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRegistrationResponse}
     */
    this.registerUserUsingPOST = function(userRegistration, opts, callback) {
      opts = opts || {};
      var postBody = userRegistration;

      // verify the required parameter 'userRegistration' is set
      if (userRegistration === undefined || userRegistration === null) {
        throw new Error("Missing the required parameter 'userRegistration' when calling registerUserUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = UserRegistrationResponse;

      return this.apiClient.callApi(
        '/account/registration', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the requestPasswordResetUsingPOST operation.
     * @callback module:api/AccountcontrollerApi~requestPasswordResetUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SimpleMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * requestPasswordReset
     * @param {module:model/PasswordResetRequest} resetRequest resetRequest
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {module:api/AccountcontrollerApi~requestPasswordResetUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SimpleMessageResponse}
     */
    this.requestPasswordResetUsingPOST = function(resetRequest, opts, callback) {
      opts = opts || {};
      var postBody = resetRequest;

      // verify the required parameter 'resetRequest' is set
      if (resetRequest === undefined || resetRequest === null) {
        throw new Error("Missing the required parameter 'resetRequest' when calling requestPasswordResetUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = SimpleMessageResponse;

      return this.apiClient.callApi(
        '/account/password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the verifyPasswordResetUsingPUT operation.
     * @callback module:api/AccountcontrollerApi~verifyPasswordResetUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SimpleMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * verifyPasswordReset
     * @param {module:model/PasswordResetVerificationRequest} verificationRequest verificationRequest
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {module:api/AccountcontrollerApi~verifyPasswordResetUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SimpleMessageResponse}
     */
    this.verifyPasswordResetUsingPUT = function(verificationRequest, opts, callback) {
      opts = opts || {};
      var postBody = verificationRequest;

      // verify the required parameter 'verificationRequest' is set
      if (verificationRequest === undefined || verificationRequest === null) {
        throw new Error("Missing the required parameter 'verificationRequest' when calling verifyPasswordResetUsingPUT");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = SimpleMessageResponse;

      return this.apiClient.callApi(
        '/account/password', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the verifyRegistrationUsingPOST operation.
     * @callback module:api/AccountcontrollerApi~verifyRegistrationUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserPresentation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * verifyRegistration
     * @param {String} username username
     * @param {module:model/RegistrationVerificationTokenPresentation} token token
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {module:api/AccountcontrollerApi~verifyRegistrationUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserPresentation}
     */
    this.verifyRegistrationUsingPOST = function(username, token, opts, callback) {
      opts = opts || {};
      var postBody = token;

      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling verifyRegistrationUsingPOST");
      }

      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling verifyRegistrationUsingPOST");
      }


      var pathParams = {
        'username': username
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = UserPresentation;

      return this.apiClient.callApi(
        '/account/verification/{username}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
