/**
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaginatedResponseUserPresentation', 'model/PaginatedResponseUserRoles'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaginatedResponseUserPresentation'), require('../model/PaginatedResponseUserRoles'));
  } else {
    // Browser globals (root is window)
    if (!root.Id4iApi) {
      root.Id4iApi = {};
    }
    root.Id4iApi.OrganizationusercontrollerApi = factory(root.Id4iApi.ApiClient, root.Id4iApi.PaginatedResponseUserPresentation, root.Id4iApi.PaginatedResponseUserRoles);
  }
}(this, function(ApiClient, PaginatedResponseUserPresentation, PaginatedResponseUserRoles) {
  'use strict';

  /**
   * Organizationusercontroller service.
   * @module api/OrganizationusercontrollerApi
   * @version 0.0.1-alpha
   */

  /**
   * Constructs a new OrganizationusercontrollerApi. 
   * @alias module:api/OrganizationusercontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getUserRolesUsingGET operation.
     * @callback module:api/OrganizationusercontrollerApi~getUserRolesUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResponseUserRoles} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getUserRoles
     * @param {Number} organizationId organizationId
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {Number} opts.offset 
     * @param {Number} opts.limit 
     * @param {module:api/OrganizationusercontrollerApi~getUserRolesUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResponseUserRoles}
     */
    this.getUserRolesUsingGET = function(organizationId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling getUserRolesUsingGET");
      }


      var pathParams = {
        'organizationId': organizationId
      };
      var queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit']
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = PaginatedResponseUserRoles;

      return this.apiClient.callApi(
        '/api/v1/organization/{organizationId}/userroles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsersUsingGET operation.
     * @callback module:api/OrganizationusercontrollerApi~getUsersUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResponseUserPresentation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getUsers
     * @param {Number} organizationId organizationId
     * @param {Object} opts Optional parameters
     * @param {String} opts.authorization Authorization JWT Bearer Token as returned from /login
     * @param {String} opts.acceptLanguage Requested language
     * @param {Number} opts.offset 
     * @param {Number} opts.limit 
     * @param {module:api/OrganizationusercontrollerApi~getUsersUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResponseUserPresentation}
     */
    this.getUsersUsingGET = function(organizationId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling getUsersUsingGET");
      }


      var pathParams = {
        'organizationId': organizationId
      };
      var queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit']
      };
      var headerParams = {
        'Authorization': opts['authorization'],
        'Accept-Language': opts['acceptLanguage']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json;charset=UTF-8'];
      var accepts = ['application/xml', 'application/json;charset=UTF-8'];
      var returnType = PaginatedResponseUserPresentation;

      return this.apiClient.callApi(
        '/api/v1/organization/{organizationId}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
