/**
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Id4iApi);
  }
}(this, function(expect, Id4iApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Id4iApi.OrganizationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationsApi', function() {
    describe('addMultipleUserRolesUsingPOST', function() {
      it('should call addMultipleUserRolesUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addMultipleUserRolesUsingPOST
        //instance.addMultipleUserRolesUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUserRolesUsingPOST', function() {
      it('should call addUserRolesUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addUserRolesUsingPOST
        //instance.addUserRolesUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createOrganzationUsingPOST', function() {
      it('should call createOrganzationUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createOrganzationUsingPOST
        //instance.createOrganzationUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationLogoUsingDELETE', function() {
      it('should call deleteOrganizationLogoUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationLogoUsingDELETE
        //instance.deleteOrganizationLogoUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationUsingDELETE', function() {
      it('should call deleteOrganizationUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationUsingDELETE
        //instance.deleteOrganizationUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAddressUsingGET', function() {
      it('should call getAddressUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAddressUsingGET
        //instance.getAddressUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsingGET', function() {
      it('should call getAllUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllUsingGET
        //instance.getAllUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBillingAddressUsingGET', function() {
      it('should call getBillingAddressUsingGET successfully', function(done) {
        //uncomment below and update the code to test getBillingAddressUsingGET
        //instance.getBillingAddressUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMultipleUserRolesUsingGET', function() {
      it('should call getMultipleUserRolesUsingGET successfully', function(done) {
        //uncomment below and update the code to test getMultipleUserRolesUsingGET
        //instance.getMultipleUserRolesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationUsingGET', function() {
      it('should call getOrganizationUsingGET successfully', function(done) {
        //uncomment below and update the code to test getOrganizationUsingGET
        //instance.getOrganizationUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsUsingGET', function() {
      it('should call getOrganizationsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsUsingGET
        //instance.getOrganizationsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserRolesByUsernameUsingGET', function() {
      it('should call getUserRolesByUsernameUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUserRolesByUsernameUsingGET
        //instance.getUserRolesByUsernameUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersUsingGET', function() {
      it('should call getUsersUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUsersUsingGET
        //instance.getUsersUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeBillingAddressUsingDELETE', function() {
      it('should call removeBillingAddressUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeBillingAddressUsingDELETE
        //instance.removeBillingAddressUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeMultipleUserRolesUsingDELETE', function() {
      it('should call removeMultipleUserRolesUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeMultipleUserRolesUsingDELETE
        //instance.removeMultipleUserRolesUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeUserRolesUsingDELETE', function() {
      it('should call removeUserRolesUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeUserRolesUsingDELETE
        //instance.removeUserRolesUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setOrganizationLogoUsingPOST', function() {
      it('should call setOrganizationLogoUsingPOST successfully', function(done) {
        //uncomment below and update the code to test setOrganizationLogoUsingPOST
        //instance.setOrganizationLogoUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeAddressUsingPOST', function() {
      it('should call storeAddressUsingPOST successfully', function(done) {
        //uncomment below and update the code to test storeAddressUsingPOST
        //instance.storeAddressUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeBillingAddressUsingPOST', function() {
      it('should call storeBillingAddressUsingPOST successfully', function(done) {
        //uncomment below and update the code to test storeBillingAddressUsingPOST
        //instance.storeBillingAddressUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateOrganizationUsingPUT', function() {
      it('should call updateOrganizationUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateOrganizationUsingPUT
        //instance.updateOrganizationUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
