/**
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Id4iApi);
  }
}(this, function(expect, Id4iApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Id4iApi.RoutingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RoutingApi', function() {
    describe('addElementsToRoutingCollectionUsingPUT', function() {
      it('should call addElementsToRoutingCollectionUsingPUT successfully', function(done) {
        //uncomment below and update the code to test addElementsToRoutingCollectionUsingPUT
        //instance.addElementsToRoutingCollectionUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addSingleElementToRoutingCollectionUsingPUT', function() {
      it('should call addSingleElementToRoutingCollectionUsingPUT successfully', function(done) {
        //uncomment below and update the code to test addSingleElementToRoutingCollectionUsingPUT
        //instance.addSingleElementToRoutingCollectionUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createRoutingCollectionUsingPOST', function() {
      it('should call createRoutingCollectionUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createRoutingCollectionUsingPOST
        //instance.createRoutingCollectionUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRoutingCollectionUsingDELETE', function() {
      it('should call deleteRoutingCollectionUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteRoutingCollectionUsingDELETE
        //instance.deleteRoutingCollectionUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findById4nUsingGET3', function() {
      it('should call findById4nUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test findById4nUsingGET3
        //instance.findById4nUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('forwardUsingGET', function() {
      it('should call forwardUsingGET successfully', function(done) {
        //uncomment below and update the code to test forwardUsingGET
        //instance.forwardUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeElementsFromRoutingCollectionUsingDELETE', function() {
      it('should call removeElementsFromRoutingCollectionUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeElementsFromRoutingCollectionUsingDELETE
        //instance.removeElementsFromRoutingCollectionUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeSingleElementFromRoutingCollectionUsingDELETE', function() {
      it('should call removeSingleElementFromRoutingCollectionUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeSingleElementFromRoutingCollectionUsingDELETE
        //instance.removeSingleElementFromRoutingCollectionUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveCurrentParamsByTypeUsingGET', function() {
      it('should call retrieveCurrentParamsByTypeUsingGET successfully', function(done) {
        //uncomment below and update the code to test retrieveCurrentParamsByTypeUsingGET
        //instance.retrieveCurrentParamsByTypeUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveRoutingFileUsingGET', function() {
      it('should call retrieveRoutingFileUsingGET successfully', function(done) {
        //uncomment below and update the code to test retrieveRoutingFileUsingGET
        //instance.retrieveRoutingFileUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeRoutingFileUsingPUT', function() {
      it('should call storeRoutingFileUsingPUT successfully', function(done) {
        //uncomment below and update the code to test storeRoutingFileUsingPUT
        //instance.storeRoutingFileUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUsingPUT3', function() {
      it('should call updateUsingPUT3 successfully', function(done) {
        //uncomment below and update the code to test updateUsingPUT3
        //instance.updateUsingPUT3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
